# Generated by Django 5.2.7 on 2026-01-24 11:00

import api.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_id', models.CharField(max_length=20)),
                ('audit_name', models.CharField(max_length=200)),
                ('objective', models.TextField()),
                ('scope', models.TextField()),
                ('date', models.DateField()),
                ('lead_auditor', models.CharField(max_length=100)),
                ('participants', models.TextField(blank=True)),
                ('standard', models.CharField(choices=[('iso-7101', 'ISO 7101'), ('iso-27001', 'ISO/IEC 27001'), ('iso-42001', 'ISO/IEC 42001')], db_index=True, default='iso-7101', max_length=20)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Scheduled', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=63, unique=True, validators=[api.models.validate_org_slug])),
                ('name', models.CharField(default='Your Organization', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('standard', models.CharField(default='iso-27001', max_length=64)),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('code', 'standard')},
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('group', models.CharField(blank=True, max_length=128)),
                ('standard', models.CharField(default='iso-27001', max_length=64)),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('code', 'standard')},
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_id', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20)),
                ('corrective_action', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('target_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='api.audit')),
                ('clause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='api.clause')),
                ('controls', models.ManyToManyField(blank=True, related_name='findings', to='api.control')),
            ],
        ),
        migrations.AddField(
            model_name='audit',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='api.organization'),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(editable=False, max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(blank=True, max_length=128, null=True)),
                ('classification', models.CharField(blank=True, choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted'), ('sensitive', 'Sensitive')], max_length=32, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('legal_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('technical_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=16, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('standard', models.CharField(default='iso-27001', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_secure', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='api.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_id', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('likelihood', models.CharField(max_length=50)),
                ('impact', models.CharField(max_length=50)),
                ('risk_score', models.FloatField()),
                ('risk_level', models.CharField(max_length=20)),
                ('existing_control', models.TextField(blank=True, null=True)),
                ('treatment_action', models.TextField(blank=True, null=True)),
                ('owner', models.CharField(max_length=100)),
                ('status', models.CharField(default='Open', max_length=50)),
                ('review_date', models.DateField()),
                ('archived', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks_7101', to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SoAEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicable', models.BooleanField(default=True)),
                ('justification', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Not Implemented', 'Not Implemented'), ('Partial', 'Partial'), ('Full', 'Full')], default='Not Implemented', max_length=32)),
                ('evidence_notes', models.TextField(blank=True)),
                ('standard', models.CharField(default='iso-27001', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soa_entries', to='api.control')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soa_entries', to='api.organization')),
            ],
            options={
                'ordering': ['control__code'],
            },
        ),
        migrations.CreateModel(
            name='TenantSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_asset_number', models.PositiveIntegerField(default=1)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sequence', to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('auditor', 'Auditor'), ('staff', 'Staff')], default='staff', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ISORisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('likelihood', models.PositiveSmallIntegerField(default=3)),
                ('impact', models.PositiveSmallIntegerField(default=3)),
                ('risk_score', models.PositiveIntegerField(blank=True, null=True)),
                ('level', models.CharField(blank=True, max_length=16)),
                ('treatment', models.CharField(blank=True, max_length=64)),
                ('owner', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(default='Open', max_length=32)),
                ('standard', models.CharField(default='iso-27001', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acceptance_justification', models.TextField(blank=True)),
                ('control_coverage', models.CharField(blank=True, default='Untreated', max_length=32)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='api.asset')),
                ('controls', models.ManyToManyField(blank=True, related_name='risks', to='api.control')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iso_risks', to='api.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'standard'], name='api_isorisk_organiz_c3d761_idx'), models.Index(fields=['organization', 'standard', 'status'], name='api_isorisk_organiz_dbebc2_idx'), models.Index(fields=['organization', 'standard', 'level'], name='api_isorisk_organiz_cd4688_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(db_index=True, max_length=64)),
                ('clause_number', models.CharField(max_length=20)),
                ('clause_major', models.PositiveSmallIntegerField(db_index=True)),
                ('clause_minor', models.PositiveSmallIntegerField(db_index=True)),
                ('short_description', models.TextField(blank=True, default='')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('NI', 'Not Implemented'), ('P', 'Planned'), ('IP', 'In Progress'), ('MI', 'Mostly Implemented'), ('O', 'Optimized')], default='NI', max_length=10)),
                ('comments', models.TextField(blank=True, null=True)),
                ('owner', models.CharField(default='Unassigned', max_length=100)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_clauses', to='api.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'standard'], name='api_complia_organiz_a4d15c_idx'), models.Index(fields=['organization', 'standard', 'clause_major', 'clause_minor'], name='api_complia_organiz_21caf1_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'standard', 'clause_number'), name='unique_clause_per_tenant_standard')],
            },
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['organization', 'standard'], name='api_audit_organiz_3b60b7_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['organization', 'status'], name='api_audit_organiz_e3bbc6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='audit',
            unique_together={('organization', 'audit_id')},
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'standard'], name='api_asset_organiz_e304f5_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'classification'], name='api_asset_organiz_450695_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'asset_type'], name='api_asset_organiz_a6e0d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('organization', 'asset_id')},
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['organization'], name='api_risk_organiz_fae155_idx'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['organization', 'status'], name='api_risk_organiz_c0e3c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='risk',
            unique_together={('organization', 'risk_id')},
        ),
        migrations.AddIndex(
            model_name='soaentry',
            index=models.Index(fields=['organization', 'standard'], name='api_soaentr_organiz_29f123_idx'),
        ),
        migrations.AddIndex(
            model_name='soaentry',
            index=models.Index(fields=['organization', 'standard', 'applicable'], name='api_soaentr_organiz_86e661_idx'),
        ),
        migrations.AddIndex(
            model_name='soaentry',
            index=models.Index(fields=['organization', 'standard', 'status'], name='api_soaentr_organiz_f5caf7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='soaentry',
            unique_together={('organization', 'control', 'standard')},
        ),
    ]
