# Generated by Django 5.2.7 on 2025-10-27 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_id', models.CharField(max_length=20, unique=True)),
                ('audit_name', models.CharField(max_length=200)),
                ('objective', models.TextField()),
                ('scope', models.TextField()),
                ('date', models.DateField()),
                ('lead_auditor', models.CharField(max_length=100)),
                ('participants', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed')], default='Scheduled', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_number', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('NI', 'Not Implemented'), ('P', 'Planned'), ('IP', 'In Progress'), ('MI', 'Mostly Implemented'), ('O', 'Optimized')], default='NI', max_length=10)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_id', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('likelihood', models.CharField(max_length=50)),
                ('impact', models.CharField(max_length=50)),
                ('risk_score', models.FloatField()),
                ('risk_level', models.CharField(max_length=20)),
                ('existing_control', models.TextField(blank=True, null=True)),
                ('treatment_action', models.TextField(blank=True, null=True)),
                ('owner', models.CharField(max_length=100)),
                ('status', models.CharField(default='Open', max_length=50)),
                ('review_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_id', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20)),
                ('corrective_action', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('target_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='api.audit')),
            ],
        ),
    ]
