# Generated by Django 5.2.7 on 2026-01-26 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISO27001ClauseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NI', 'Not Implemented'), ('P', 'Planned'), ('IP', 'In Progress'), ('MI', 'Mostly Implemented'), ('O', 'Optimized')], default='NI', max_length=10)),
                ('owner', models.CharField(default='Unassigned', max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/iso27001/clauses/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_records', to='api.clause')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iso27001_clause_records', to='api.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization'], name='api_iso2700_organiz_298e61_idx'), models.Index(fields=['organization', 'status'], name='api_iso2700_organiz_36b47d_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'clause'), name='uniq_iso27001_clause_record_per_tenant')],
            },
        ),
    ]
