# Generated by Django 5.2.7 on 2025-11-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
