# Generated by Django 5.2.7 on 2026-02-01 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_iso27001clauserecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='audit',
            unique_together={('organization', 'standard', 'audit_id')},
        ),
    ]
