# Generated by Django 5.2.7 on 2025-11-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_risk_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceclause',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complianceclause',
            name='owner',
            field=models.CharField(default='Unassigned', max_length=100),
        ),
    ]
