# Generated by Django 5.2.7 on 2026-02-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_audit_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformUpdate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('feature', 'Feature'), ('bugfix', 'Bug Fix'), ('announcement', 'Announcement'), ('maintenance', 'Maintenance')], default='announcement', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Update',
                'verbose_name_plural': 'Platform Updates',
                'ordering': ['-date'],
            },
        ),
    ]
