# Generated by Django 5.2.7 on 2025-11-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_complianceclause_comments_complianceclause_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceclause',
            name='short_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
