# Generated by Django 5.2.7 on 2026-02-05 11:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_platformupdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(help_text='e.g. Cloud Provider, SaaS, Consultant', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('scope_of_dependency', models.TextField(help_text='How the organization depends on this third party (operations, finance, legal, strategic, etc.)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('review_frequency_months', models.PositiveIntegerField(default=12, help_text='Planned review frequency in months')),
                ('next_review_due', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tprm_third_parties', to='api.organization')),
                ('relationship_owner', models.ForeignKey(blank=True, help_text='Internal owner responsible for the relationship', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tprm_owned_third_parties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Third Party',
                'verbose_name_plural': 'Third Parties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TPRMAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_type', models.CharField(choices=[('questionnaire', 'Questionnaire'), ('certification', 'Certification'), ('contract_review', 'Contract Review'), ('external_report', 'External Report'), ('other', 'Other')], max_length=50)),
                ('summary', models.TextField(help_text='High-level outcome / notes')),
                ('assessment_date', models.DateField()),
                ('valid_until', models.DateField(blank=True, help_text='Optional expiry date for assurance', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tprm_assessments', to=settings.AUTH_USER_MODEL)),
                ('third_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tprm_assessments', to='api.thirdparty')),
            ],
            options={
                'verbose_name': 'TPRM Assessment',
                'verbose_name_plural': 'TPRM Assessments',
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='TPRMDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accept'), ('mitigate', 'Mitigate'), ('transfer', 'Transfer'), ('avoid', 'Avoid')], default='pending', max_length=20)),
                ('justification', models.TextField(blank=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tprm_approved_decisions', to=settings.AUTH_USER_MODEL)),
                ('third_party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tprm_decision', to='api.thirdparty')),
            ],
            options={
                'verbose_name': 'TPRM Decision',
                'verbose_name_plural': 'TPRM Decisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TPRMRisk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('risk_type', models.CharField(choices=[('operational', 'Operational'), ('security', 'Security'), ('financial', 'Financial'), ('legal', 'Legal / Regulatory'), ('strategic', 'Strategic'), ('reputational', 'Reputational')], max_length=30)),
                ('likelihood', models.PositiveSmallIntegerField(help_text='Likelihood on a 1–5 scale', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('impact', models.PositiveSmallIntegerField(help_text='Impact on a 1–5 scale', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('inherent_risk_score', models.PositiveSmallIntegerField(help_text='Computed as likelihood × impact')),
                ('residual_risk_score', models.PositiveSmallIntegerField(blank=True, help_text='Optional; set after assessment/decision', null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('mitigated', 'Mitigated'), ('accepted', 'Accepted'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tprm_risks', to=settings.AUTH_USER_MODEL)),
                ('third_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tprm_risks', to='api.thirdparty')),
            ],
            options={
                'verbose_name': 'TPRM Risk',
                'verbose_name_plural': 'TPRM Risks',
                'ordering': ['-inherent_risk_score', 'title'],
            },
        ),
    ]
